# Generated by Django 4.0.4 on 2022-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('Serving', models.IntegerField()),
                ('Description', models.TextField()),
                ('Method', models.TextField()),
                ('Picture', models.ImageField(upload_to='files/covers')),
            ],
        ),
    ]
